version: '3.8'

services:
  mqtt-broker:
    image: frostfire_mqtt-broker
    build:
      context: .
      dockerfile: Dockerfile.mosquitto
    container_name: frostfire_mqtt-broker_container
    ports:
      - "1883:1883"
      - "8083:8083"  # WebSocket port
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/letsencrypt/live/hicsvntdracons.xyz/fullchain.pem:/mosquitto/config/certs/mosquitto.crt
      - /etc/letsencrypt/live/hicsvntdracons.xyz/privkey.pem:/mosquitto/config/certs/mosquitto.key 
      - ./ssl/dhparam2048.pem:/mosquitto/config/certs/dhparam.pem
      # - ./ssl/certs/insecure.pem:/mosquitto/config/certs/mosquitto.crt
      # - ./ssl/private/insecure.key:/mosquitto/config/certs/mosquitto.key 
      # - ./ssl/dhparam2048.pem:/mosquitto/config/certs/dhparam.pem
    environment:
      - CERT_PATH=/mosquitto/config/certs
    restart: unless-stopped

  frostfire-iot-hub:
    image: frostfire_iot_hub
    build:
      context: .
    container_name: frostfire_iot_hub_container
    environment:
      HOST: "0.0.0.0"  # Bind to all interfaces
      PORT: "8443"      # Use port 8443 in production for HTTPS    
      MQTT_BROKER: "mqtt-broker"  # Adjust based on your setup
      MQTT_PORT: "1883"
      MQTT_TOPIC: "domus/devices"
      SSL_KEYFILE: "/etc/letsencrypt/live/hicsvntdracons.xyz/privkey.pem"
      SSL_CERTFILE: "/etc/letsencrypt/live/hicsvntdracons.xyz/fullchain.pem"
    volumes:
      - /etc/letsencrypt/live/hicsvntdracons.xyz/privkey.pem:/etc/letsencrypt/live/hicsvntdracons.xyz/privkey.pem:ro
      - /etc/letsencrypt/live/hicsvntdracons.xyz/fullchain.pem:/etc/letsencrypt/live/hicsvntdracons.xyz/fullchain.pem:ro
      # If you have DH parameters, include them as well
      - /etc/ssl/dhparam.pem:/etc/letsencrypt/live/hicsvntdracons.xyz/dhparam.pem:ro
    ports:
      - "8443:8443"
    command: python run.py  # Adjust based on your entry point
    restart: unless-stopped